package bci_bpm_cob.model;
//import org.drools.runtime.process.WorkItem;
//import org.drools.runtime.process.WorkItemHandler;
//import org.drools.runtime.process.WorkItemManager;
import org.kie.api.runtime.process.WorkItem;
import org.kie.api.runtime.process.WorkItemManager;
import org.kie.api.runtime.process.WorkItemHandler;
import java.util.Map;
import java.util.HashMap;


/**
 * This class was automatically generated by the data modeler tool.
 */

public class CalculadoraWorkItemHandler  implements WorkItemHandler {

    public void executeWorkItem(WorkItem workItem, WorkItemManager manager){
        
        // Obtener valores  
        Integer var1 = (Integer) workItem.getParameter("Variable1");
        Integer var2 = (Integer) workItem.getParameter("Variable2");
        String op = (String) workItem.getParameter("Operador");
        String resultado = (String) workItem.getParameter("Resultado");
        
        // Operar  
       //  workItem.setParameter(Resultado, "Resultado de prueba" );
        //String resultado = (String) workItem.getParameter("Resultado");
        
        // notificar al wI manager
        Map<String, Object> results = new HashMap<String, Object>();
        results.put("resultado", new Integer(10));

        manager.completeWorkItem(workItem.getId(), results);
        
    }

 public void abortWorkItem(WorkItem workItem, WorkItemManager manager) {
    // gg
    manager.abortWorkItem(workItem.getId());
  }
}   


 
 