package bci_bpm_cob.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class OperacionWIH implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public OperacionWIH() {
    }

}