package bci_bpm_cob;

import org.drools.core.event.DefaultAgendaEventListener;
import org.kie.api.definition.rule.Rule;
import org.kie.api.event.rule.AfterMatchFiredEvent;
import org.kie.api.runtime.rule.Match;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("cliente")
public class Cliente implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Nombre")
   private java.lang.String nombre;
   @org.kie.api.definition.type.Label(value = "Ejecutivo Comercial")
   private java.lang.String ejcomercial;

   public Cliente()
   {
   }

   public java.lang.String getNombre()
   {
      return this.nombre;
   }

   public void setNombre(java.lang.String nombre)
   {
      this.nombre = nombre;
   }

   public java.lang.String getEjcomercial()
   {
      return this.ejcomercial;
   }

   public void setEjcomercial(java.lang.String ejcomercial)
   {
      this.ejcomercial = ejcomercial;
   }

   public Cliente(java.lang.String nombre, java.lang.String ejcomercial)
   {
      this.nombre = nombre;
      this.ejcomercial = ejcomercial;
   }

}